# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectionset.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_exdec(QDialog):
    signal = pyqtSignal(bool)

    def __init__(self, standard):
        self.standard = standard
        super(Ui_exdec, self).__init__()
        self.setupUi(self)
        self.radioButton.toggled.connect(self.change)  # 信号：当状态改变时。连接信号和槽

    def setupUi(self, detectwin):
        detectwin.setObjectName("detectwin")
        detectwin.resize(270, 204)
        self.verticalLayoutWidget = QtWidgets.QWidget(detectwin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 70, 171, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.label = QtWidgets.QLabel(detectwin)
        self.label.setGeometry(QtCore.QRect(30, 30, 151, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(detectwin)
        self.buttonBox.setGeometry(QtCore.QRect(100, 160, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.radioButton_2.setChecked(True)
        self.buttonBox.accepted.connect(self.acceptwin)
        self.buttonBox.rejected.connect(self.rejectwin)

        self.retranslateUi(detectwin)
        QtCore.QMetaObject.connectSlotsByName(detectwin)

    def retranslateUi(self, detectwin):
        _translate = QtCore.QCoreApplication.translate
        detectwin.setWindowTitle(_translate("detectwin", "检测设置"))
        self.radioButton_2.setText(_translate("detectwin", "NIST SP800-22r1a"))
        self.radioButton.setText(_translate("detectwin", "国密GM/T 0005-2021"))
        self.label.setText(_translate("detectwin", "随机数检测标准"))

    def change(self):
        if self.radioButton_2.isChecked():  # NIST检测是否选中
            self.standard = True
        else:
            self.standard = False

    def acceptwin(self):
        self.signal.emit(self.standard)
        self.accept()

    def rejectwin(self):
        self.reject()