# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'entropyset.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class Ui_widget(QDialog):
    signal = pyqtSignal(list, list)

    def __init__(self, lst, para):
        super(Ui_widget, self).__init__()
        self.setupUi(self)
        self.list = lst
        self.para = para

    def setupUi(self, accesswin):
        accesswin.setObjectName("accesswin")
        accesswin.resize(369, 383)
        self.label_2 = QtWidgets.QLabel(accesswin)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 151, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(accesswin)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(50, 60, 111, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.min = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.min.setFont(font)
        self.min.setAutoFillBackground(False)
        self.min.setChecked(True)
        self.min.setObjectName("min")
        self.verticalLayout.addWidget(self.min)
        self.shannon = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.shannon.setFont(font)
        self.shannon.setAutoFillBackground(False)
        self.shannon.setChecked(True)
        self.shannon.setObjectName("shannon")
        self.verticalLayout.addWidget(self.shannon)
        self.sample = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.sample.setFont(font)
        self.sample.setAutoFillBackground(False)
        self.sample.setChecked(True)
        self.sample.setObjectName("sample")
        self.verticalLayout.addWidget(self.sample)
        self.renyi = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.renyi.setFont(font)
        self.renyi.setChecked(True)
        self.renyi.setObjectName("renyi")
        self.verticalLayout.addWidget(self.renyi)
        self.buttonBox = QtWidgets.QDialogButtonBox(accesswin)
        self.buttonBox.setGeometry(QtCore.QRect(170, 320, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.sample_e = QtWidgets.QLineEdit(accesswin)
        self.sample_e.setGeometry(QtCore.QRect(170, 130, 113, 20))
        self.sample_e.setObjectName("sample_q")
        self.sample_embedding = QtWidgets.QLabel(accesswin)
        self.sample_embedding.setGeometry(QtCore.QRect(170, 110, 211, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sample_embedding.setFont(font)
        self.sample_embedding.setObjectName("sample_embedding")
        self.sample_tolerance = QtWidgets.QLabel(accesswin)
        self.sample_tolerance.setGeometry(QtCore.QRect(170, 160, 211, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.sample_tolerance.setFont(font)
        self.sample_tolerance.setObjectName("sample_tolerance")
        self.sample_t = QtWidgets.QLineEdit(accesswin)
        self.sample_t.setGeometry(QtCore.QRect(170, 180, 113, 20))
        self.sample_t.setObjectName("sample_q_2")
        self.sample_para = QtWidgets.QLabel(accesswin)
        self.sample_para.setGeometry(QtCore.QRect(160, 80, 151, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.sample_para.setFont(font)
        self.sample_para.setObjectName("sample_para")
        self.renyi_order = QtWidgets.QLabel(accesswin)
        self.renyi_order.setGeometry(QtCore.QRect(170, 260, 211, 20))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.renyi_order.setFont(font)
        self.renyi_order.setObjectName("renyi_order")
        self.renyi_para = QtWidgets.QLabel(accesswin)
        self.renyi_para.setGeometry(QtCore.QRect(160, 230, 151, 16))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        self.renyi_para.setFont(font)
        self.renyi_para.setObjectName("renyi_para")
        self.renyi_o = QtWidgets.QLineEdit(accesswin)
        self.renyi_o.setGeometry(QtCore.QRect(170, 280, 113, 20))
        self.renyi_o.setObjectName("sample_q_3")
        self.buttonBox.accepted.connect(self.acceptwin)
        self.buttonBox.rejected.connect(self.rejectwin)

        self.retranslateUi(accesswin)
        QtCore.QMetaObject.connectSlotsByName(accesswin)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "熵评估设置"))
        self.label_2.setText(_translate("widget", "评估种类"))
        self.min.setText(_translate("widget", "最小熵"))
        self.shannon.setText(_translate("widget", "香农熵"))
        self.sample.setText(_translate("widget", "样本熵"))
        self.renyi.setText(_translate("widget", "瑞丽熵"))
        self.sample_embedding.setText(_translate("widget", "embedding dimension:"))
        self.sample_tolerance.setText(_translate("widget", "tolerance:"))
        self.sample_para.setText(_translate("widget", "样本熵参数"))
        self.renyi_order.setText(_translate("widget", "order"))
        self.renyi_para.setText(_translate("widget", "瑞丽熵参数"))

    # def change_e(self):
    #     self.para[0] = self.sample_e.text()
    #
    # def change_t(self):
    #     self.para[1] = self.sample_t.text()
    #
    # def change_o(self):
    #     self.para[2] = self.renyi_o.text()

    def acceptwin(self):
        if self.min.isChecked():  # 复选框选中判断
            self.list[0] = 1
        if self.shannon.isChecked():
            self.list[1] = 1
        if self.sample.isChecked():
            self.list[2] = 1
        if self.renyi.isChecked():
            self.list[3] = 1

        self.para[0] = self.sample_e.text()  # 接收输入参数
        self.para[1] = self.sample_t.text()
        self.para[2] = self.renyi_o.text()
        if self.sample.isChecked() and self.para[0] is None:
            self.para[0] = 0
        if self.sample.isChecked() and self.para[1] is None:
            self.para[1] = 0
        if self.renyi.isChecked() and self.para[2] is None:
            self.para[2] = 0
        self.signal.emit(self.list, self.para)
        self.accept()

    def rejectwin(self):
        self.reject()
